// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfqxbavmmxsuvutkoyzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmcXhiYXZtbXhzdXZ1dGtveXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODQzMjQsImV4cCI6MjA2MjU2MDMyNH0.e8To89rvnAgrqmw_5DPZX_et1zFykY-JRC7CtDI40j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);